export const mdas = [
  {
    mda_id: "3",
    title: "PLATEAU STATE INTERNAL REVENUE SERVICE",
    reg_number: "101000",
    date_created: "1628777239",
    date_updated: "1628777239",
    created_by: null,
    slug: "plateau-state-internal-revenue-service",
  },
  {
    mda_id: "121",
    title: "PLATEAU STATE UNIVERSITY, BOKKOS",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-state-university-bokkos",
  },
  {
    mda_id: "122",
    title: "MINISTRY OF AGRICULTURE AND RURAL",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "ministry-of-agriculture-and-rural",
  },
  {
    mda_id: "124",
    title: "MINISTRY OF LANDS, SURVEY AND TOWN",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "ministry-of-lands-survey-and-town",
  },
  {
    mda_id: "125",
    title: "PLATEAU STATE POLYTECHNIC, BARKIN LADI (MAIN/HRDC",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-state-polytechnic-barkin-ladi-main-hrdc",
  },
  {
    mda_id: "126",
    title: "MINISTRY OF EDUCATION  AND  ERC PLATEAU STATE",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "ministry-of-education-and-erc-plateau-state",
  },
  {
    mda_id: "127",
    title: "COLLEGE OF EDUCATION, GINDIRI - PLATEAU ",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "college-of-education-gindiri-plateau",
  },
  {
    mda_id: "128",
    title: "MINISTRY OF TRANSPORT - PLATEAU STATE",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "ministry-of-transport-plateau-state",
  },
  {
    mda_id: "129",
    title: "PLATEAU STATE HOSPITALS MANAGEMENT BOARD",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-state-hospitals-management-board",
  },
  {
    mda_id: "130",
    title: "PLATEAU STATE WATER BOARD",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-state-water-board",
  },
  {
    mda_id: "131",
    title: "PLATEAU RADIO TELEVISION CORPORATION-RADIO",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-radio-television-corporation-radio",
  },
  {
    mda_id: "132",
    title: "PLATEAU STATE SPECIALIST HOSPITAL",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-state-specialist-hospital",
  },
  {
    mda_id: "133",
    title: "COLLEGE OF NURSING AND MIDWIFERY, VOM - ",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "college-of-nursing-and-midwifery-vom",
  },
  {
    mda_id: "134",
    title: "PLATEAU RADIO TELEVISION CORPORATION-TV",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-radio-television-corporation-tv",
  },
  {
    mda_id: "135",
    title: "JOS METROPOLITAN DEVELOPMENT BOARD - ",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "jos-metropolitan-development-board",
  },
  {
    mda_id: "136",
    title: "PLATEAU STATE PUBLISHING CORPORATION",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-state-publishing-corporation",
  },
  {
    mda_id: "137",
    title: "COLLEGE OF HEALTH TECHNOLOGY, PANKSHIN - ",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "college-of-health-technology-pankshin",
  },
  {
    mda_id: "138",
    title: "COLLEGE OF HEALTH TECHNOLOGY, ZAWAN - ",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "college-of-health-technology-zawan",
  },
  {
    mda_id: "139",
    title: "MINISTRY OF MINERAL DEVELOPMENT",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "ministry-of-mineral-development",
  },
  {
    mda_id: "140",
    title: "MINISTRY OF FINANCE - BUREAU FOR BUDGET PLATEAU STATE ",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "ministry-of-finance-bureau-for-budget-plateau-state",
  },
  {
    mda_id: "141",
    title: "OFFICE OF THE HEAD OF CIVIL SERVICE - PLATEAU ",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "office-of-the-head-of-civil-service-plateau",
  },
  {
    mda_id: "142",
    title: "PLATEAU STATE UNIVERSAL BASIC EDUCATION",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-state-universal-basic-education",
  },
  {
    mda_id: "143",
    title: "PLATEAU UNITED FOOTBALL CLUB",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-united-football-club",
  },
  {
    mda_id: "144",
    title: "COLLEGE OF ARTS, SCIENCE AND TECHNOLOGY, KURGWI",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "college-of-arts-science-and-technology-kurgwi",
  },
  {
    mda_id: "145",
    title: "PLATEAU STATE TOURISM CORPORATION",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-state-tourism-corporation",
  },
  {
    mda_id: "146",
    title: "MINISTRY OF WATER RESOURCES AND ENERGY - ",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "ministry-of-water-resources-and-energy",
  },
  {
    mda_id: "147",
    title: "HIGH COURT OF JUSTICE - PLATEAU STATE ",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "high-court-of-justice-plateau-state",
  },
  {
    mda_id: "148",
    title: "MINISTRY OF WORKS - PLATEAU STATE ",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "ministry-of-works-plateau-state",
  },
  {
    mda_id: "149",
    title: "KABONG MARKET",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "kabong-market",
  },
  {
    mda_id: "150",
    title: "PLATEAU STATE RURAL WATER SUP & SAN AGENCY",
    reg_number: null,
    date_created: "1620664539",
    date_updated: "1620664539",
    created_by: null,
    slug: "plateau-state-rural-water-sup-san-agency",
  },
  {
    mda_id: "151",
    title: "COLLEGE OF AGRICULTURE, GARKAWA - PLATEAU ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "college-of-agriculture-garkawa-plateau",
  },
  {
    mda_id: "152",
    title: "PLATEAU STATE INDEPENDENT ELECTORAL ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-independent-electoral",
  },
  {
    mda_id: "153",
    title: "MINISTRY OF ENVIRONMENT ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "ministry-of-environment",
  },
  {
    mda_id: "154",
    title: "MINISTRY FOR LOCAL GOVERNMENT AND CHIFTANCY",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "ministry-for-local-government-and-chiftancy",
  },
  {
    mda_id: "155",
    title: "MINISTRY OF TOURISM, CULTURE AND HOSPT.",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "ministry-of-tourism-culture-and-hospt",
  },
  {
    mda_id: "156",
    title: "MINISTRY OF PHYSICAL PLANNING AND URBAN DEVELOPMENT ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "ministry-of-physical-planning-and-urban-development",
  },
  {
    mda_id: "157",
    title: "PLATEAU STATE MICROFINANCE DEV AGENCY",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-microfinance-dev-agency",
  },
  {
    mda_id: "158",
    title: "PLATAEU AGRICULTURAL MECHANIZATION",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plataeu-agricultural-mechanization",
  },
  {
    mda_id: "159",
    title: "OFFICE OF THE SECRETARY TO THE GOVERNMENT",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "office-of-the-secretary-to-the-government",
  },
  {
    mda_id: "160",
    title: "MINISTRY OF EDU. SCI & TECH - (HIGHER EDUCATION)",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "ministry-of-edu-sci-tech-higher-education",
  },
  {
    mda_id: "161",
    title: "MINISTRY OF JUSTICE - PLATEAU STATE ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "ministry-of-justice-plateau-state",
  },
  {
    mda_id: "162",
    title: "PLATEAU STATE ENVIRONMENTAL PROTECTION ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-environmental-protection",
  },
  {
    mda_id: "163",
    title: "PLATEAU STATE BUREAU OF PUBLIC PROCUREMENT",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-bureau-of-public-procurement",
  },
  {
    mda_id: "164",
    title: "MINISTRY OF HEALTH - PLATEAU STATE ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "ministry-of-health-plateau-state",
  },
  {
    mda_id: "165",
    title: "PLATEAU AGRICULTURAL DEVELOPMENT PROGRAMME ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-agricultural-development-programme",
  },
  {
    mda_id: "166",
    title: "PLATEAU STATE SPORTS COUNCIL",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-sports-council",
  },
  {
    mda_id: "167",
    title: "MINISTRY OF HOUSING - PLATEAU STATE ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "ministry-of-housing-plateau-state",
  },
  {
    mda_id: "168",
    title: "PLATEAU STATE CHRISTIAN PILGRIMS WELFARE ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-christian-pilgrims-welfare",
  },
  {
    mda_id: "169",
    title: "PLATEAU STATE MUSLIM PILGRIMS WELFARE ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-muslim-pilgrims-welfare",
  },
  {
    mda_id: "170",
    title: "PLATEAU STATE SCHOLARSHIP BOARD",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-scholarship-board",
  },
  {
    mda_id: "171",
    title: "PLATEAU STATE TEACHERS SERVICE COMMISSION",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-teachers-service-commission",
  },
  {
    mda_id: "172",
    title: "PLATEAU STATE FIRE SERVICE DIRECTORATE",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-fire-service-directorate",
  },
  {
    mda_id: "173",
    title: "JOS MAIN MARKET AUTHORITY - PLATEAU STATE ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "jos-main-market-authority-plateau-state",
  },
  {
    mda_id: "174",
    title: "PLATEAU STATE AUDIT DEPARTMENT",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-audit-department",
  },
  {
    mda_id: "175",
    title: "MINISTRY OF YOUTH AND SPORTS DEVELOPMENT - ",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "ministry-of-youth-and-sports-development",
  },
  {
    mda_id: "176",
    title: "PLATEAU STATE ROAD MAINTENANCE AGENCY",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "plateau-state-road-maintenance-agency",
  },
  {
    mda_id: "177",
    title: "MINISTRY OF INFORMATION AND COMMUNICATION",
    reg_number: null,
    date_created: "1620664540",
    date_updated: "1620664540",
    created_by: null,
    slug: "ministry-of-information-and-communication",
  },
  {
    mda_id: "178",
    title: "PLATEAU STATE LOCAL GOVERNMENT STAFF PENSION BOARD",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "plateau-state-local-government-staff-pension-board",
  },
  {
    mda_id: "179",
    title: "PLATEAU STATE RELEVANT TECH BOARD",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "plateau-state-relevant-tech-board",
  },
  {
    mda_id: "180",
    title: "CUSTOMARY COURT OF APPEAL",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "customary-court-of-appeal",
  },
  {
    mda_id: "181",
    title: "MINISTRY OF WOMEN AFFAIRS AND SOCIAL ",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "ministry-of-women-affairs-and-social",
  },
  {
    mda_id: "182",
    title: "PLATEAU STATE CIVIL SERVICE COMMISSION",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "plateau-state-civil-service-commission",
  },
  {
    mda_id: "183",
    title: "SHARIA COURT OF APPEAL - PLATEAU STATE ",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "sharia-court-of-appeal-plateau-state",
  },
  {
    mda_id: "184",
    title: "PLATEAU STATE HOUSE OF ASSEMBLY COMMISSION",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "plateau-state-house-of-assembly-commission",
  },
  {
    mda_id: "185",
    title: "PLATEAU STATE LOCAL GOVERNMENT SERVICE ",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "plateau-state-local-government-service",
  },
  {
    mda_id: "186",
    title: "PLATEAU STATE DISABILITY RIGHTS COMMISSION",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "plateau-state-disability-rights-commission",
  },
  {
    mda_id: "187",
    title: "PLATEAU STATE LOCAL GOVERNMENT AUDIT",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "plateau-state-local-government-audit",
  },
  {
    mda_id: "188",
    title: "MINISTRY OF BUDGET AND ECONOMIC PLANNING",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "ministry-of-budget-and-economic-planning",
  },
  {
    mda_id: "189",
    title: "JUDICIAL SERVICE COMMISSION",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "judicial-service-commission",
  },
  {
    mda_id: "190",
    title: "PLATEAU STATE AIDS CONTROL AGENCY",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "plateau-state-aids-control-agency",
  },
  {
    mda_id: "191",
    title: "PRIMARY HEALTH CARE DEVELOPMENT",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "primary-health-care-development",
  },
  {
    mda_id: "192",
    title: "PLATEAU STATE ADULT AND NON FORMAL.",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "plateau-state-adult-and-non-formal",
  },
  {
    mda_id: "193",
    title: "PLATEAU STATE LIBRARY BOARD",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "plateau-state-library-board",
  },
  {
    mda_id: "194",
    title: "PLATEAU STATE AFORESTATION PROGRAMME",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "plateau-state-aforestation-programme",
  },
  {
    mda_id: "195",
    title: "OFFICE OF THE ACCOUNTANT GENERAL - PLATEAU ",
    reg_number: null,
    date_created: "1620664541",
    date_updated: "1620664541",
    created_by: null,
    slug: "office-of-the-accountant-general-plateau",
  },
  {
    mda_id: "196",
    title: "PLATEAU STATE BUREAU OF STATISTICS",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "plateau-state-bureau-of-statistics",
  },
  {
    mda_id: "197",
    title: "GOVERNMENT SECONDARY SCHOOLS",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "government-secondary-schools",
  },
  {
    mda_id: "198",
    title: "PLATEAU STATE PEACE BUILDING AGENCY",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "plateau-state-peace-building-agency",
  },
  {
    mda_id: "199",
    title: "MINISTRY OF COMMERCE AND INDUSTRIES - ",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "ministry-of-commerce-and-industries",
  },
  {
    mda_id: "200",
    title: "OFFICE OF THE DEPUTY GOVERNOR - PLATEAU ",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "office-of-the-deputy-governor-plateau",
  },
  {
    mda_id: "201",
    title: "OFFICE OF THE AUDITOR GENERAL - PLATEAU ",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "office-of-the-auditor-general-plateau",
  },
  {
    mda_id: "202",
    title: "OFFICE OF THE GOVERNOR - PLATEAU STATE ",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "office-of-the-governor-plateau-state",
  },
  {
    mda_id: "203",
    title: "PANKSHIN GENERAL HOSPITAL, PANKSHIN - ",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "pankshin-general-hospital-pankshin",
  },
  {
    mda_id: "204",
    title: "PLATEAU STATE COMMUNITY AND SOCIAL ",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "plateau-state-community-and-social",
  },
  {
    mda_id: "205",
    title: "PLATEAU STATE ICT DEVELOPMENT AGENCY",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "plateau-state-ict-development-agency",
  },
  {
    mda_id: "206",
    title: "PLATEAU STATE BOUNDARY COMMISSION",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "plateau-state-boundary-commission",
  },
  {
    mda_id: "207",
    title: "PLATEAU STATE HOUSE OF ASSEMBLY",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "plateau-state-house-of-assembly",
  },
  {
    mda_id: "208",
    title: "MINISTRY OF SCIENCE AND TECHNOLOGY",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "ministry-of-science-and-technology",
  },
  {
    mda_id: "209",
    title: "PLATEAU STATE DEBT MANAGEMENT DEPT",
    reg_number: null,
    date_created: "1620664542",
    date_updated: "1620664542",
    created_by: null,
    slug: "plateau-state-debt-management-dept",
  },
  {
    mda_id: "210",
    title: "PLATEAU STATE OPERATION RAINBOW",
    reg_number: null,
    date_created: "1620664543",
    date_updated: "1620664543",
    created_by: null,
    slug: "plateau-state-operation-rainbow",
  },
  {
    mda_id: "211",
    title: "PLATEAU STATE PENSION BOARD",
    reg_number: null,
    date_created: "1620664543",
    date_updated: "1620664543",
    created_by: null,
    slug: "plateau-state-pension-board",
  },
  {
    mda_id: "212",
    title: "PLATEAU STATE PLANNING COMMISSION",
    reg_number: null,
    date_created: "1620664543",
    date_updated: "1620664543",
    created_by: null,
    slug: "plateau-state-planning-commission",
  },
  {
    mda_id: "213",
    title: "PLATEAU STATE PRINTING PRESS",
    reg_number: null,
    date_created: "1620664543",
    date_updated: "1620664543",
    created_by: null,
    slug: "plateau-state-printing-press",
  },
  {
    mda_id: "214",
    title: "PLATEAU STATE SCHOOL FOR THE DEAF",
    reg_number: null,
    date_created: "1620664543",
    date_updated: "1620664543",
    created_by: null,
    slug: "plateau-state-school-for-the-deaf",
  },
  {
    mda_id: "215",
    title: "SECONDARY EDUCATION",
    reg_number: null,
    date_created: "1620664543",
    date_updated: "1620664543",
    created_by: null,
    slug: "secondary-education",
  },
  {
    mda_id: "216",
    title: "PL EMERGENCY RELIEF AND MGT AGENCY",
    reg_number: null,
    date_created: "1620664543",
    date_updated: "1620664543",
    created_by: null,
    slug: "pl-emergency-relief-and-mgt-agency",
  },
];
